### PR TITLE
58 refactor voting changes

### PR DESCRIPTION
**Pull request by bimalghartimagar**

### CODE REVIEW

**Comment by juanpabloventoso** [comment]
@bimalghartimagar looks good. However, I found that the voting icons are showing/hiding the opposite way than expected. If I check "disable voting", then the icons show. If I uncheck it, they hide. Should be the other way around. Hopefully that's a quick fix?

**Comment by bimalghartimagar** [comment]
@juanpabloventoso good catch! I have made the fixes for you to review. Thank you.

**Comment by bimalghartimagar** [comment]
@juanpabloventoso I also made changes to update empty archive email property for channel after Dylan made changes to the BE to accept empty value.

**Comment by dylanwooters** [comment]
@bimalghartimagar This is working well in my local. Merging this in. Thanks!

**Pull request merged**
